export const XP_CONFIG = {
  STAGE_COMPLETE: 50,
  MISSION_COMPLETE_BONUS: 150,
  WORLD_COMPLETE_BONUS: 500,
  DAILY_STREAK_BONUS: 25,
  NO_HINTS_MISSION_BONUS: 75,
  SPEED_BONUS: 50,
  DAILY_CHALLENGE_COMPLETE: 100,
  FIRST_CODE_RUN: 10,
  PUBLISH_PROJECT: 30,
  FIRST_LOGIN_OF_DAY: 15,
} as const;
